import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const fontsMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Futsalkeun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontsMontserrat.variable} antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
