import type { Metadata } from "next";
import { Graduate } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image"

const fontsGraduate = Graduate({
  variable: "--font-graduate",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Futsalkeun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontsGraduate.variable} antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
